services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emumba_qor
      MYSQL_USER: d2s
      MYSQL_PASSWORD: D2s_1234!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://d2s:D2s_1234!@db/emumba_qor
    depends_on:
      - db
    volumes:
      - .:/app  # Map the current directory to /app in the container

# Define the named volume
volumes:
  db_data:
