name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    # Run Unit Tests
    - name: Run tests
      run: |
        chmod +x runtest.sh  
        ./runtest.sh         
        echo "Tests passed successfully!"
      

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t flask-app -f PROJECT/Dockerfile ./PROJECT  # Correct Dockerfile path

    # Deploy Container
    - name: Deploy Container
      run: |
         docker-compose -f PROJECT/docker-compose.yml up -d  # Use correct docker-compose path

  notify:
    needs: [build, dockerize]
    runs-on: ubuntu-latest

    steps:
    # Send Email Notification
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.taskeen }}
        password: ${{ secrets.taskeen_pass }}
        subject: CI/CD Pipeline Passed
        body: |
          Hello,
          The CI/CD pipeline for your Flask app has passed successfully!
        to: taskeen.zehra@emumba.com
