name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker to build and run the application
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my_app .

      # Run tests using your existing runtest.sh script
      - name: Run Newman tests and send email report
        run: |
          chmod +x ./runtest.sh  # Ensure the script is executable
          ./runtest.sh           # Execute the script

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy the application (if needed)
      - name: Deploy the application
        run: |
          docker-compose up -d

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      # Send success email notification
      - name: Send success email
        run: |
          echo "Pipeline Passed" | mail -s "CI/CD Pipeline Status" taskeen.zehra@emumba.com
